# Generated by Django 4.2.7 on 2024-06-24 18:06

import account.utils
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sex',
        ),
        migrations.AddField(
            model_name='advisor',
            name='Type',
            field=models.CharField(choices=[('FIN', 'Financial'), ('TECH', 'Technical'), ('STRAT', 'Strategic'), ('LEGAL', 'Legal')], default='Mr', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisor',
            name='ownership',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_path',
            field=cloudinary.models.CloudinaryField(default='default', max_length=255, validators=[account.utils.file_validation], verbose_name='image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('HRH', 'HRH'), ('Sheikh', 'Sheikh')], default='Mr', max_length=10),
        ),
        migrations.AlterField(
            model_name='founder',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='founders', to='account.industry'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='investors', to='account.industry'),
        ),
    ]
