# Generated by Django 4.2.7 on 2024-06-25 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_image_remove_customuser_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.CharField(choices=[('FIN', 'Financial'), ('TECH', 'Technical'), ('STRAT', 'Strategic'), ('LEGAL', 'Legal'), ('HR', 'Human Resources'), ('MARK', 'Marketing'), ('SALES', 'Sales'), ('OTHER', 'Other')], max_length=5)),
                ('ownership', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Advisor',
                'verbose_name_plural': 'Advisors',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('stage', models.CharField(choices=[('ideation', 'Ideation'), ('mvp', 'MVP'), ('growth', 'Growth')], max_length=100)),
                ('country', models.CharField(max_length=150)),
                ('industry', models.CharField(choices=[('finTech', 'FinTech'), ('agriTech', 'AgriTech'), ('edTech', 'EdTech')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Founding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(blank=True, max_length=150, null=True)),
                ('Biography', models.TextField(blank=True, null=True)),
                ('ownership', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='founders', to='account.company')),
            ],
            options={
                'verbose_name': 'Founding',
                'verbose_name_plural': 'Foundings',
            },
        ),
        migrations.CreateModel(
            name='Investing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regain_period', models.DateField(blank=True, null=True)),
                ('best_roi', models.IntegerField(blank=True, null=True)),
                ('maximum_drop_invalue', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('growth', 'Long-term Growth'), ('income', 'Regular Income'), ('speculation', 'Short-term Speculation'), ('diversification', 'Portfolio Diversification'), ('other', 'Other')], max_length=20)),
                ('other_purpose', models.CharField(blank=True, max_length=100)),
                ('investment_date', models.DateField(auto_now_add=True)),
                ('amount_of_investment', models.IntegerField(blank=True, null=True)),
                ('other_industries', models.CharField(blank=True, max_length=100)),
                ('ownership', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('industries', models.ManyToManyField(blank=True, related_name='Investings', to='account.industry')),
            ],
            options={
                'verbose_name': 'Investing',
                'verbose_name_plural': 'Investings',
            },
        ),
        migrations.RemoveField(
            model_name='founder',
            name='industries',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='industries',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Networth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
        migrations.DeleteModel(
            name='Founder',
        ),
        migrations.DeleteModel(
            name='Investor',
        ),
        migrations.DeleteModel(
            name='Shareholder',
        ),
        migrations.AddField(
            model_name='founding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='founders', to=settings.AUTH_USER_MODEL),
        ),
    ]
