# Generated by Django 4.2.7 on 2024-07-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_advising_company_founding_investing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founding',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
