# Generated by Django 4.2.7 on 2024-07-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, choices=[('finTech', 'FinTech'), ('agriTech', 'AgriTech'), ('edTech', 'EdTech')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='stage',
            field=models.CharField(blank=True, choices=[('ideation', 'Ideation'), ('mvp', 'MVP'), ('growth', 'Growth')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
